### PR TITLE
Windows Console Titles

### PR DESCRIPTION
**Pull request by adqm**
I played around with this a bit on Windows, running directly from within `cmd`.  For me, `cmd` was having trouble with the window titles (the text was just being printed to the console, escape sequence and all).  I believe this should fix those issues.  Will include more comments in your original PR.

### CODE REVIEW

**Comment by rbrewer123** [comment]
Thanks for working on that.  I've gotten so used to running within ConEmu (an alternate terminal emulator for Windows) that I forgot to test in a vanilla cmd.exe window.  It'll be a couple days before I'm back at my machine to do some more testing.

**Comment by adqm** [comment]
I added here a simple job control system that at least allows keeping track of background processes and moving them to the foreground.  It seems like suspending a process (equivalent of ^z on *nix) is hard, so I'll leave that for another day.

**Comment by rbrewer123** [comment]
Thanks, that's nice and your improvements are working well for me.  I was having a minor issue in ConEmu when I switched focus from a cmd.exe window to a ConEmu window.  It seemed like the cursor flashed rapidly as if it were trying to catch up or something.   It seems to be mitigated by allowing xonsh to continue using the ANSI title sequences when it detects ConEmu is available.  I'll continue addressing the other issues you and @scopatz mentioned for my main PR.

**Comment by rbrewer123** [comment]
@wrywerytwreywery by the way, I now think the cursor flashing rapidly issue is a ConEmu bug...

**Pull request merged**
