### PR TITLE
Merge from scopatz master (and 1 other change)

### PR DESCRIPTION
**Pull request by adqm**
I think this should accomplish the merge (including fixing merge conflicts).  I also made some changes to `jobs.py` to avoid rechecking `ON_WINDOWS` in each of the functions; if you don't want to merge that change in, you can just revert my last commit on this branch.

Haven't tested outside of Windows yet, so I might push some more here if something turns out to be broken.

### CODE REVIEW

**Comment by rbrewer123** [comment]
Thanks for doing that!  On my Windows setup I'm getting nosetest errors about Handle() being undefined in proc.py.  It looks like it isn't needed, so I removed all calls to Handle().  Now I'm getting 'bad file descriptor' in the call to io.open() in proc.py.  Would you see if you can reproduce these?

**Comment by adqm** [comment]
I think those `Handle` calls should probably stay there, but we need the code for that class as well (it also comes from `subprocess.py`.  I've just pushed something that I think should fix (though I will not be around a Windows computer to test until tomorrow evening).

**Comment by rbrewer123** [comment]
Thanks, that fixed the Handle() issue.  I'm still seeing the bad file descriptor issue.

**Comment by rbrewer123** [comment]
Seems to be working well now, thanks for helping with that merge!

**Pull request merged**
